### ISSUE TITLE
Beat Counter Non-functional

### ISSUE THREAD

**Issue by mysteryblock** [ErikMinekus/traktor-kontrol-screens#11]
Fresh install, followed installation instructions, and this beat counter does not seem to work. 

(By beat-counter I am referring to the 1 red and 3 yellow boxes up top and the --.- next to it)

**Comment by mysteryblock** [comment]
I've figured out the issue. Seems to have been related to the D2s defaulting to A/B & C/D after installation, as oppoised to the factory A/C/ B/D format. Once I switched my two units back to a factory deck layout the beat counter began to work. However, it does seem to only show on the last deck you've pressed play on. It would be wonderful it it always counter on both units.

**Comment by ErikMinekus** [comment]
The beat counter on the Nexus mod is for the master deck, so it only shows when you're looking at a deck which is not the master.
