### ISSUE TITLE
Traktor 3.2 Bugs

### ISSUE THREAD

**Issue by DJ5D** [ErikMinekus/traktor-kontrol-screens#13]
Kontrol S5 now shows "undefined" where the Camelot key should be shown, when attempting to change keys.

**Comment by DJ5D** [comment]
@ErikMinekus when is the fix happening? Can you share with me your work so I can try and solve this?

**Comment by DJ5D** [comment]
THANK YOU FOR THE UPDATE!! :)

**Comment by ErikMinekus** [comment]
Sorry for the delay, it was quite a pain to properly display Camelot keys after the 3.2 update. Every other mod I've seen will just display ERR or undefined when the key knob is between .05 and .95.
