### ISSUE TITLE
Qml interference with Pioneer Cdj 2000 nxs'2 HID

### ISSUE THREAD

**Issue by mikmash** [ErikMinekus/traktor-kontrol-screens#14]
Hi I run Traktor 3.2.0 with two CDJ 2000 nexus 2's in Hid mode, I have added a Kontrol D2 and want to change the screen layout to the Nexus edition qml hack.  Would this interefere with the screen read outs on the Hid Cdj's waveform etc. or just alter the kontrol D2 layout etc?

Thanks.

![traktor--hid-update jpg optimal](https://user-images.githubusercontent.com/54846534/64172610-48299880-ce4d-11e9-9e62-91fbea9cd83c.jpg)

**Comment by ErikMinekus** [comment]
No, these mods don't interfere with CDJs in HID.
