### ISSUE TITLE
loss of Nexus display to another after update

### ISSUE THREAD

**Issue by mikmash** [ErikMinekus/traktor-kontrol-screens#18]
HI I updated to Traktor 3.3.0 which failed, I followed and downloaded the new update for the nexus but I have a different display this time it looks a lot like the prime version.  Is there a folder I specifically need to copy and paste?

**Comment by ErikMinekus** [comment]
The Nexus version is here: https://github.com/ErikMinekus/traktor-kontrol-screens/tree/nexus

I will update the readme with links to the different versions.

**Comment by mikmash** [comment]
Thankyou
