### ISSUE TITLE
Rating songs from directly from the controller (s5)

### ISSUE THREAD

**Issue by Alwin75** [ErikMinekus/traktor-kontrol-screens#22]
The goal is while playing (without laptopscreen, lit closed) songs from a large library to mark nice songs.
 
Is it possible to map a (shift) hardware button on the controller to directly rate a playing song with for example 5 stars?

**Comment by Alwin75** [comment]
The goal is to let people search (a part of) the database and mark request songs on small parties. 

Is it possible to let people search the database, or a part of the database and mark songs so that the dj can see somewehere in traktor requests coming in. 

possible solution, thinking outloud:
Maybe let people searching through a webserver database (copy of traktor database) and then through api put the request in some dedicated traktor playlist or something...

**Comment by ErikMinekus** [comment]
Unfortunately the rating can only be displayed in the browser, there's no way to change the rating of a track.
