### ISSUE TITLE
archivo

### ISSUE THREAD

**Issue by dongi3940** [ErikMinekus/traktor-kontrol-screens#25]
donde esta para  descargar el archivo??

**Comment by ErikMinekus** [comment]
<img width="910" alt="Screen Shot 2022-05-01 at 21 23 33" src="https://user-images.githubusercontent.com/1819481/166161526-6f9b11e1-89af-4048-ae39-44b79f449d3f.png">

**Comment by dongi3940** [comment]
Gracias
