### ISSUE TITLE
Nexus: Beat counter animation stopped working on S5 -  Traktor 3.11.1 17 

### ISSUE THREAD

**Issue by bogdanlalu** [ErikMinekus/traktor-kontrol-screens#29]
The 4 beat counter rectangles constantly appear blank and no longer fill up in line with the beats (still works on Prime).
![IMG_20240524_151427__01](https://github.com/ErikMinekus/traktor-kontrol-screens/assets/16867980/69b840aa-d47e-423e-b3ad-3ac2b9696275)

**Comment by ErikMinekus** [comment]
The beat counter in the Nexus mod shows the beats of the master deck, and therefore does not work when you are looking at the master deck, because you can already see the beats in the waveform.
