### ISSUE TITLE
Easy access to Mixer FX on S8 and S5

### ISSUE THREAD

**Issue by drcain1** [ErikMinekus/traktor-kontrol-screens#30]
With the Supreme mod, you could just hit (shift?) [FX Select] to access the mixer FX menu for the current deck, is it possible to implement something similar in this mod? 
It guess it might not be as easy since it would need to output the current possible mixer FX selections for this to be usable.
This is mainly for the S8 and maybe S5.
It's pretty much the only missing feature that I was relying on. I have since midi-mapped shift+mixer fx knob to mixer fx selection but it would be nice to have some feedback through the screens on the device.

**Comment by ErikMinekus** [comment]
I have considered implementing this before, it's not that difficult. The only problem is I would need to periodically parse the `Traktor Settings.tsi` file to get the names of the Mixer FX configured in Traktor's preferences. I will look into it.

**Comment by ErikMinekus** [comment]
Using my Kontrol mod, Shift+FX Select will now display a Mixer FX overlay on the S8 and D2 (the S5 doesn't have an FX Select button). I will merge it to the Nexus and Prime mods at a later point.

Unfortunately the latest Traktor Pro 3 versions do not allow us to read the `Traktor Settings.tsi` file to get the configured Mixer FX in Traktor's preferences, so you will have to specify those manually in `Defines/Prefs.qml`.
