### ISSUE TITLE
Hey Erik does this work with Traktor Pro 4 

### ISSUE THREAD

**Issue by michaelkmusic** [ErikMinekus/traktor-kontrol-screens#31]
Hey Erik just curious does this work with TP4 and the D2's ?

TIA

**Comment by ErikMinekus** [comment]
Hi Michael,

I did a comparison of the QML files the other day and it looks like the S8, S5 and D2 are not affected. The double tap to load stems is only implemented in newer controllers. I just did a quick test with my mod on TP4 and things seemed to work as expected.

If you are using an S8/S5/D2 together with a newer controller like the S4/X1 MK3 or a CDJ/XDJ you may be missing out on the double tap gesture if you use my mod, but other than that there shouldn't be any issues. I'm worried that implementing that gesture will make my mod incompatible with Traktor Pro 3, so I'm not planning to do that until Traktor Pro 4 matures.

**Comment by michaelkmusic** [comment]
Okay thanks again this is awesome looking forward to updates in the future!  I am loving the new TP4 :)
