### ISSUE TITLE
Key number is off and incorrect on S8 with July 24 screen mod

### ISSUE THREAD

**Issue by RealFutureSelf** [ErikMinekus/traktor-kontrol-screens#32]
Noticed the computer screen shows 1M and the controller screen for the track displays 8M.

**Comment by ErikMinekus** [comment]
Do you have a picture? By default Camelot notation is on in my mods, so 1m showing as 8A is correct.

**Comment by RealFutureSelf** [comment]
Thank you for the response. I've struggled with using the mod and possibly
it's my freshman knowledge of it all.

I was hoping to have the keys match on the controller and computer. I don't
have any options to change in order to match.

The waveform colors don't seem to match between controller and computer
screen.

Stems waveforms do not show on the controller display.

Appreciate your feedback of you can help.  If not, I understand.

**Comment by ErikMinekus** [comment]
> I was hoping to have the keys match on the controller and computer. I don't have any options to change in order to match.

You can change the value of `camelotKey` to `false` in the Defines/Prefs.qml file.

> The waveform colors don't seem to match between controller and computer screen.

The controller displays are not capable of displaying the same colors as the computer, by default they're always blue. But with my mod you have some waveform color options to pick from in Defines/Prefs.qml.

> Stems waveforms do not show on the controller display.

This has been a bug in Traktor for years, it also happens without my mod. As a workaround you can press the top right button next to the display twice to get them to show up.

**Comment by RealFutureSelf** [comment]
Thanks Erik!  Awesome, I made the qml change and will use it. Appreciate
your guidance on the other items too.

**Comment by RealFutureSelf** [comment]
Hi Erik,
Do you happen to know if the S8 mods work for Traktor 4?

**Comment by ErikMinekus** [comment]
Yes, see #31.
