### ISSUE TITLE
Display the musical key on the deck screen, in addition to the browser screen

### ISSUE THREAD

**Issue by alza-bitz** [ErikMinekus/traktor-kontrol-screens#6]
It would be useful to see the musical key on the deck screen for reference, since when browsing into other playlists on the other deck screen that doesn't contain the currently playing track, the musical key won't be visible..

As in, with the current screens, the only way to see the musical key of the currently playing track is to refer to the playlist that contains it on the browser screen, which isn't ideal when you're looking into other playlists for the next track.

**Comment by ErikMinekus** [comment]
I want to keep the master mod close to the original displays, so I have no plans to display the key on the deck screen. My other mods, [Nexus](https://github.com/ErikMinekus/traktor-kontrol-screens/tree/nexus#screenshots) and [Prime](https://github.com/ErikMinekus/traktor-kontrol-screens/tree/prime#screenshots), do display the key in the deck header.

**Comment by raakaveli** [comment]
is it possible to show the musical key on the nexus or prime display as the musical key (sharp), not camelot?

**Comment by ErikMinekus** [comment]
I have now added a preferences file, where you can disable Camelot Keys.
