### ISSUE TITLE
Traktor 3 Update

### ISSUE THREAD

**Issue by Voidsnap** [ErikMinekus/traktor-kontrol-screens#8]
Hey, do u updating the Mod for traktor 3, cant wait to Play Traktor 3 with the Prime display Mod :D.

Btw thanks a lot for this amaszing mod.

**Comment by tobse91** [comment]
Doesnt work for me on Traktor Pro 3 either :( On Pro 2 everything's working superb

**Comment by ErikMinekus** [comment]
The Nexus and Prime mods have now been updated for Traktor 3.
